version: "2"
services:
  collectd:
    build: .
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hostname:/host/hostname:ro
      - /proc:/host/proc:ro
networks:
  default:
    external:
      name: ${LOGSTASH_NETWORK}
